### ISSUE TITLE
Add `nohash` to benchmarks

### ISSUE THREAD

**Issue by Glitchy-Tozier** [tkaitchuck/aHash#115]
https://docs.rs/nohash/0.2.0/nohash/index.html

It would be interesting to see how nohash_hasher compares to aHash and under which circumstances which one of them should be preferred.

**Comment by tkaitchuck** [comment]
Well, it's very hard to compare because obviously doing nothing is infinitely faster than doing anything. Obviously nohash only works if the data is effectively already random, which is very application specific. So there isn't really a way to have a 'representative' level of randomness in keys to test because each map is likely to be totally different. 

To compare absolute length of time, when hashing inputs that are just a single number, on most any CPU, aHash should be able to complete in under 10 cpu cycles and under 5 on the sorts most people use. Obviously comparing 5 to 0 seems huge, but what else is the application doing in the loop? If it's a map large enough or the values boxed and this results in the value not being in the cpu cache, then whatever loop is being run will be waiting 100+ cycles to fetch that anyway and so the hasing time won't really be a factor in the overall performance. If that is not the case and there are loads of lookups in a very small map in a tight loop then it could be a very large factor.

**Comment by Glitchy-Tozier** [comment]
Thank you for the detailed response, should we close the issue, then?
