### ISSUE TITLE
Using with neither `compile-time-rng` or `runtime-rng` features.

### ISSUE THREAD

**Issue by Anders429** [tkaitchuck/aHash#123]
I'm trying to understand how to upgrade my `ahash` dependency version to the newly released version `0.8.0`, and want to know what the recommended practice is. On version `0.7`, I was able to just use `ahash` as a dependency, and when I compiled on a `no_std` target that wasn't supported by `getrandom`, it seems `ahash` was nicely resolving that issue for me.

However, now when I upgrade to `0.8.0`, `no_std` support for my library is broken when I enable `runtime-rng`. So I am thinking that the correct way to handle this would be to just depend on `ahash` with neither `compile-time-rng` or `runtime-rng` set, so that constant keys are used by default (as documented in the [`Cargo.toml` file](https://github.com/tkaitchuck/aHash/blob/master/Cargo.toml#L36)), and that would leave consumers of my library free to enable whatever rng generation features they want downstream. But, despite what the `Cargo.toml` says, setting neither of the rng features means that I can't actually create a new `RandomState` using `ahash::RandomState::new()`, because the `new()` method is [feature-gated by at least one of those features](https://github.com/tkaitchuck/aHash/blob/master/src/random_state.rs#L213).

Looking at the source code, there doesn't seem to be a specific reason why it would need to be feature-gated, because `get_fixed_seeds()` would just [return the constant seeds](https://github.com/tkaitchuck/aHash/blob/master/src/random_state.rs#L102-L104), as expected, so I am wondering whether this feature-gating on the `new()` method is intentional or not, or perhaps I am missing something. 

My expectation was that I could just use `ahash::RandomState::new()` in my library, and no matter which rng feature was set, or if neither were set, it would still create a `RandomState` for me to use, similar to what `ahash` was doing implicitly on version `0.7`.

**Comment by tkaitchuck** [comment]
Yes. This is the major API change in the 0.8 release. Previously it attempted to look at the OS / Flags to infer when getrandom was available and use it. In 0.8 it no long does this and simply leaves it up to the feature flags. This was done because the automation logic proved inconvenient for some applications.

If neither runtime-rng or compile-time-rng is set, then there are no random constants available as base value so instead of relying on `RandomState::new()` which uses these random fixed constants `RandomState::generate_with()` is available so that the application may provide such values directly. (Note that the values passed to `generate_with` may be fixed constants, and it will still result in different states each time.)

In terms of security strength `runtime-rng` is obviously best followed by `compile-time-rng`. But the flag `runtime-rng` will implicitly disable `compile-time-rng`. So if you have a library that needs to work in a no-std environment that does need DOS resistance, then depending on `compile-time-rng` is reasonable because if an upstream application enables `runtime-rng` it will automatically enable, and the compiled output will be constant as normal. If anything beyond minimal DOS resistance is not required then just pass fixed keys into `generate_with` and you will get the same behaviour as it had in 0.7.

**Comment by Anders429** [comment]
Thanks for the explanation. The main cause for my question was use in no-std environments. I initially assumed that I ought to use the `runtime-rng` feature, but that didn't work in my no-std environment test. I wasn't sure if `compile-time-rng` was what I wanted, since it wasn't enabled when I was using `0.7`. Your explanation was very helpful. I was able to get things working the way I wanted with the `compile-time-rng` feature.

For the record, I like this change in the new version. It's good for me to actually think about what the hasher is doing when I'm using it.
