### ISSUE TITLE
ahash features are non-additive

### ISSUE THREAD

**Issue by eric-seppanen** [tkaitchuck/aHash#138]
The documentation seems to state that features are non-additive:
> If both `runtime-rng` and `compile-time-rng` are enabled the `runtime-rng` will take precedence and `compile-time-rng` will do nothing.

That seems like a violation of Cargo's guidance that features should be *additive*. For example, if I want the `compile-time-rng` feature, but one of my dependencies (or another crate in my workspace) uses the default features, my attempt to get a compile-time rng will be silently overridden.

I didn't see an issue discussing this, but I'm also not sure this is a realistic concern. Is the compile-time rng intended only for `no_std` environments where `getrandom` isn't available, or would it be valid to use that feature on other targets too?

**Comment by schungx** [comment]
I have recently been hit by this.

I have specified `default-features = false` and `compile-time-rng` for `ahash`, only to find that it didn't work.  After a lot of trouble-shooting, I discovered that another dependency crate has `ahash` deep down its dependency, and that `ahash` has default.  Which means the default features get merged into my `ahash`.

There is no easy solution to this.  Even renaming the crate to, say, `ahash2` doesn't prevent this merging of features.  It must be separated into different source repo's in order to bypass this.

**Comment by tkaitchuck** [comment]
I am not sure how this can be observed externally, or in what sense it violates policies. 

There are two apis which are enabled if either `compile-time-rng` or `runtime-rng` are enabled. So if `runtime-rng` is turned on by another package, there is no change to the API surface. 

Depending on which flag is set it will either use `getrandom` or a random constant for the fixed seeds. But that is an internal implementation detail that can't be observed in any way. (How could you tell the difference between two sources of random numbers?) 

This could be noticed because `getrandom` is downloaded a dependency. But that would happen no matter what if there is another package depending on the `runtime-rng` feature.

So, @schungx I am not sure what you mean by "only to find that it didn't work". What didn't work?

**Comment by schungx** [comment]
What I mean is that the features are not strictly additive. As one _overrides_ the other. That's not additive.

I have seen a crate being very careful to only specify `compile-time-rng` because it needs one.

However, some dependency down the tree also uses `ahash` with default, which is `runtime-rng`. This overrides the other feature when cargo merges them.

So that crate no longer works properly and this is very hard to debug. In fact, many non-additive cargo feature issues are hard to debug .

**Comment by tkaitchuck** [comment]
> In other words, the feature compile-time-rng means the lack of randomness. 

It does not. You misunderstand the design. The flag merely indicates the source of the seed for the generator of the random keys used in the maps. If your map is created by `HashMap::default()` it will always (regardless of flags) have a unique set of keys. So even if there were no other flags anywhere on your path, each hashmap would have a unique set of keys. 

You can alter this behavior, but not using flags. See the documentation here: 
https://docs.rs/ahash/0.8.1/ahash/random_state/struct.RandomState.html
and here:
https://docs.rs/ahash/0.8.1/ahash/random_state/trait.RandomSource.html

**Comment by utkarshgupta137** [comment]
We want to use just the `AHasher` to create unique identifiers for some data deterministically across multiple machines. We came across this issue as well that `compile-time-rng` has no effect.

It seems like me & some other people are getting confused between keys, seeds, & src.
If I'm correct, keys are the final thing this is stored & used for hashing. Seeds are the compile time or runtime randomness controlled using the feature flags & src is a random number generator which operates on top of seeds. So keys are created based on seeds & src. It does not help that the API is `with_seed` when it actually means `with_key`.

So, it is true that if the compile-time-rng is enabled & runtime-rng is disabled, then the AHashMap would still've different keys. But this is not true for the AHasher. The solution for us is to use the https://docs.rs/ahash/latest/ahash/random_state/struct.RandomState.html#method.with_seeds API to create AHashers with fixed keys, but it is not very convenient.
I think either new APIs for this should be added or this distinction should be properly explained in the docs at least.
