### ISSUE TITLE
Consider reducing the size of RandomState

### ISSUE THREAD

**Issue by arthurprs** [tkaitchuck/aHash#158]
Do you think it's possible to reduce the size of RandomState? Could ahash get away with only 16 bytes maybe?  Right now it's 32 bytes long, which is twice as much as the std lib version.

This might seem inconsequential, but it can add significant overhead when ahash hashmaps are used inside repeated/nested structures.

**Comment by tkaitchuck** [comment]
It is a cpu tradeoff. It is possible to reduce the size to 16 bytes, but it will add additional instructions that need to be done on each hash. 
Introduce a feature flag for it isn't great either because it forces the whole application into one or the other. We could have an alternate HashBuilder, but it would be manual everywhere you want to use the code.

**Comment by arthurprs** [comment]
A separated HashBuilder sounds reasonable :+1:

**Comment by tkaitchuck** [comment]
@arthurprs Can you confirm this work: https://github.com/tkaitchuck/aHash/pull/226

**Comment by arthurprs** [comment]
Closedia via #226 Thank you!
