### ISSUE TITLE
Comparison to AEGIS?

### ISSUE THREAD

**Issue by luizberti** [tkaitchuck/aHash#160]
The AEGIS MAC function can be used as a keyed hashing function, and very similarly to aHash it uses AES instructions to be fast.

Frank Denis has [some benchmarks showing it as a significantly faster alternative to BLAKE3](https://github.com/jedisct1/aegis-128X#authentication-mac-1), and while these hashes are definitely not within the same niche as aHash, it would be very interesting and helpful if you (@tkaitchuck) could comment and contrast its design to that of aHash.

It would be exceptionally helpful for people who wish to port aHash's design to new languages, and to understand the design choices that were made in each one.

Cheers.

Reference: https://eprint.iacr.org/2023/523.pdf

**Comment by tkaitchuck** [comment]
They are very different with different goals. Where AEGIS is trying to:
- Be cryptographically secure
- Have a fixed standard which can be used over a network
- Deal with large volumes of data where spawning threads is an appropriate way to increase throughput. 

AHash is for use inside of in memory hashmaps so it:
- Does not care about being cryptographically secure
- Does not need a fixed standard
- Is very concerned about latency especially for small inputs
- Generally doesn't deal with very large items, so spawning a thread would be totally inappropriate. 
- Cares a lot about minimizing memory footprint

So where a AEGIS implementation may use independent state channels and spin up threads to increase parallelism, this really isn't an option for aHash. Similarly it will have to perform 10 rounds of AES per block for to provide cryptographic guarantees. Where as with some clever design aHash manages to get by with just one. Similarly it works based on a fixed standard, where as aHash will use different algorithms depending on the hardware available and the input length in order to reduce overall latency, because there is no requirement that bytes hash the same way as i32s for example.
