### ISSUE TITLE
Significant bump in MSRV from 0.8.7 to 0.8.8

### ISSUE THREAD

**Issue by schungx** [tkaitchuck/aHash#207]
Bumping Rust compiler version requirement from 1.60 to 1.72 seems too big a jump and without warning...

I believe a lot of software that depends on `ahash` must now move their MSRV upwards to 1.72 or limit to 0.8.7...

Is there a way to avoid moving to Rust 1.72?

**Comment by TomAFrench** [comment]
+1, doing this in a patch release has completely broken our release pipeline.

**Comment by tkaitchuck** [comment]
@schungx this was done to deal with https://github.com/tkaitchuck/aHash/issues/195 which was caused by https://github.com/tkaitchuck/aHash/issues/200 dispite https://github.com/tkaitchuck/aHash/pull/201 which was introduced in https://github.com/tkaitchuck/aHash/pull/183 which was added because it was a blocking issue. As a result the build was successful on X86 with all rust versions but on ARM was working on 1.60 and 1.72 and later but was broken on 1.71. 

@tnull @TomAFrench The code should still work on 1.63, you should be able to use it as-is. Is there a way to simply override the check?

**Comment by bkstein** [comment]
Or pipeline also broke and it is not easy to update rustc in the build containers. ahash is not directly specified in our Cargo.toml. It's a dependency of actix-web, which unfortunately specifies `ahab = "0.8"` without the patch version. Best for us would be renaming 0.8.8 to 0.9, but not sure, if this is somehow possible.

**Comment by chyyran** [comment]
We’re unable support Debian Testing at the moment which has a rustc of 1.70.0.

**Comment by tkaitchuck** [comment]
@chyyran @bkstein @tnull @TomAFrench Can one of you confirm that this: https://github.com/tkaitchuck/aHash/pull/208 fixes the issue for you?

**Comment by schungx** [comment]
Maybe add an MSRV CI?

**Comment by bkstein** [comment]
@tkaitchuck Thanks for the quick fix. And sorry for not checking it earlier. But it can confirm, that it works for us. :+1:
