### ISSUE TITLE
[Feature request] Runtime detection of aes

### ISSUE THREAD

**Issue by kdy1** [tkaitchuck/aHash#46]
Currently it's slower than fxhash if aes is not enabled.
Is there a plan to use detect if cpu supports aes in the runtime?

**Comment by tkaitchuck** [comment]
On my computer it is faster than fxhash (see https://github.com/tkaitchuck/aHash#speed ) with the exception of hashing primitives such as u64. However as explained here: https://github.com/tkaitchuck/aHash#fxhash it really isn't a good idea to use fxhash for these these. So I think it is reasonable to use aHash and the use compiler flags to turn on aes instructions.

Whether or not it compiles with aes instructions is dependent on compilation flags, not the actual runtime. In theory it would be possible to dynamically load a different library at runtime which is compiled in two different ways. However there is no way to do this that is transparent to applications, nor without significant overhead. This is because generally when compiling, hashing gets inlined into the callsite which improves performance quite a bit.

**Comment by kdy1** [comment]
> On my computer it is faster than fxhash (see https://github.com/tkaitchuck/aHash#speed ) with the exception of hashing primitives such as u64. However as explained here: https://github.com/tkaitchuck/aHash#fxhash it really isn't a good idea to use fxhash for these these. So I think it is reasonable to use aHash and the use compiler flags to turn on aes instructions.

In my case, key was very small. I tried ahash because hashmap.get was first entry in perf report. I'm not sure it's safe to turn on aes instruction. As it's 2020, it may be safe but, well, I don't know well about cpu's special features.
(I'll see if rustc uses it)


> Whether or not it compiles with aes instructions is dependent on compilation flags, not the actual runtime. In theory it would be possible to dynamically load a different library at runtime which is compiled in two different ways. However there is no way to do this that is transparent to applications, nor without significant overhead. This is because generally when compiling, hashing gets inlined into the callsite which improves performance quite a bit.

Thanks for the information. I didn't thought about overhead of dynamic loading.


Closing as it will be slower due to overhead.
